export type Category =
  | 'gaba-oolong'
  | 'light-oolong'
  | 'dark-oolong'
  | 'dong-ding'
  | 'red'
  | 'white'
  | 'aged'
  | 'competition'
  | 'gaba-special'
  | 'shu-puerh'
  | 'collectible-puerh';

export const categoryOrder: Category[] = [
  'gaba-oolong',
  'light-oolong',
  'dark-oolong',
  'dong-ding',
  'red',
  'white',
  'aged',
  'competition',
  'gaba-special',
  'shu-puerh',
  'collectible-puerh',
];

export type ProductStatus = 'new' | 'seasonal' | 'sold-out';

type Localized = {
  name: string;
  subtitle: string;
  origin: string;
  cultivar?: string;
  altitude?: string;
  style: string;
  year?: string;
  storage?: string;
  notes: string;
  description: string[];
  brewing?: string;
  seoTitle: string;
  seoDesc: string;
};

export type Product = {
  slug: string;
  category: Category;
  image: string;
  /** Additional gallery images for horizontal scroll carousel */
  images?: string[];
  /** slug of the producer from lib/producers.ts */
  producer?: string;
  status?: ProductStatus;
  featured?: boolean;
  ru: Localized;
  en: Localized;
};

export const products: Product[] = [
  {
    slug: 'gaba-alishan-white-currant',
    category: 'gaba-oolong',
    image: '/images/products/gaba-currant.jpg',
    ru: {
      name: 'ГАБА «Али Шань — Белая смородина»',
      subtitle: 'GABA Alishan · White Currant',
      origin: 'Тайвань, Алишань',
      altitude: '1500 м',
      style: 'ГАБА-улун',
      notes: 'Чёрная смородина, лёгкая кислинка, сладкое послевкусие',
      description: [
        'Яркий ягодный профиль с нотами чёрной смородины, лёгкой кислинкой и сладким послевкусием.',
      ],
      brewing: '90–93 °C · 5 г / 100 мл · 15–25 сек',
      seoTitle: 'ГАБА «Али Шань — Белая смородина» | EstasTea',
      seoDesc: 'ГАБА «Али Шань — Белая смородина» — Яркий ягодный профиль с нотами чёрной смородины, лёгкой кислинкой и сладким послевкусием. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Alishan — White Currant”',
      subtitle: 'GABA Alishan · White Currant',
      origin: 'Taiwan, Alishan',
      altitude: '1,500 m',
      style: 'GABA oolong',
      notes: 'Blackcurrant, light acidity, sweet finish',
      description: [
        'A bright berry profile with blackcurrant notes, a light acidity and a sweet finish.',
      ],
      brewing: '90–93 °C · 5 g / 100 ml · 15–25 sec',
      seoTitle: 'GABA “Alishan — White Currant” | EstasTea',
      seoDesc: 'GABA “Alishan — White Currant” — A bright berry profile with blackcurrant notes, a light acidity and a sweet finish. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-alishan-black-currant',
    category: 'gaba-oolong',
    image: '/images/products/gaba-alishan-black-currant.jpg',
    ru: {
      name: 'ГАБА «Али Шань — Чёрная смородина»',
      subtitle: 'GABA Alishan · Black Currant',
      origin: 'Тайвань, Алишань',
      altitude: '1500 м',
      style: 'ГАБА-улун',
      notes: 'Мёд, цветочные полутона, ягодная сладость',
      description: [
        'Медовые тона, округлый вкус с цветочными полутонами и мягкой ягодной сладостью.',
      ],
      seoTitle: 'ГАБА «Али Шань — Чёрная смородина» | EstasTea',
      seoDesc: 'ГАБА «Али Шань — Чёрная смородина» — Медовые тона, округлый вкус с цветочными полутонами и мягкой ягодной сладостью. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Alishan — Black Currant”',
      subtitle: 'GABA Alishan · Black Currant',
      origin: 'Taiwan, Alishan',
      altitude: '1,500 m',
      style: 'GABA oolong',
      notes: 'Honey, floral half-tones, berry sweetness',
      description: [
        'Honeyed tones and a rounded taste with floral half-tones and a soft berry sweetness.',
      ],
      seoTitle: 'GABA “Alishan — Black Currant” | EstasTea',
      seoDesc: 'GABA “Alishan — Black Currant” — Honeyed tones and a rounded taste with floral half-tones and a soft berry sweetness. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-secret',
    category: 'gaba-oolong',
    image: '/images/products/gaba-secret.jpeg',
    status: 'sold-out',
    ru: {
      name: 'ГАБА «Секрет»',
      subtitle: 'GABA Secret · Шань Лин Си',
      origin: 'Тайвань, Шань Лин Си',
      altitude: '1600 м',
      style: 'ГАБА-улун',
      notes: 'Цветы, фрукты, медовая округлость',
      description: [
        'Нежный и утончённый чай с цветочным ароматом, фруктовыми оттенками и медовой округлостью.',
      ],
      brewing: '90–95 °C · 5 г / 100 мл · 20–30 сек',
      seoTitle: 'ГАБА «Секрет» | EstasTea',
      seoDesc: 'ГАБА «Секрет» — Нежный и утончённый чай с цветочным ароматом, фруктовыми оттенками и медовой округлостью. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Secret”',
      subtitle: 'GABA Secret · Shan Lin Xi',
      origin: 'Taiwan, Shan Lin Xi',
      altitude: '1,600 m',
      style: 'GABA oolong',
      notes: 'Florals, fruit, honeyed roundness',
      description: [
        'A delicate, refined tea with a floral aroma, fruity shades and a honeyed roundness.',
      ],
      brewing: '90–95 °C · 5 g / 100 ml · 20–30 sec',
      seoTitle: 'GABA “Secret” | EstasTea',
      seoDesc: 'GABA “Secret” — A delicate, refined tea with a floral aroma, fruity shades and a honeyed roundness. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-green-oolong',
    category: 'gaba-oolong',
    image: '/images/products/gaba-green-oolong.jpg',
    ru: {
      name: 'GABA Green Oolong',
      subtitle: 'Азотная ферментация · Алишань',
      origin: 'Тайвань, Алишань',
      style: 'ГАБА, зелёный',
      notes: 'Карамелизированная груша, тёплые злаки, маслянистость',
      description: [
        'Нежный зелёный чай с гор Алишань, прошедший уникальную азотную ферментацию.',
        'Маслянистый вкус с нотами карамелизированной груши и тёплых злаков.',
      ],
      seoTitle: 'GABA Green Oolong | EstasTea',
      seoDesc: 'GABA Green Oolong — Нежный зелёный чай с гор Алишань, прошедший уникальную азотную ферментацию. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA Green Oolong',
      subtitle: 'Nitrogen fermentation · Alishan',
      origin: 'Taiwan, Alishan',
      style: 'GABA, green',
      notes: 'Caramelised pear, warm grain, oily body',
      description: [
        'A delicate green tea from the Alishan mountains, made with a distinctive nitrogen fermentation.',
        'An oily taste with notes of caramelised pear and warm grain.',
      ],
      seoTitle: 'GABA Green Oolong | EstasTea',
      seoDesc: 'GABA Green Oolong — A delicate green tea from the Alishan mountains, made with a distinctive nitrogen fermentation. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-eastern-riddle',
    category: 'gaba-oolong',
    image: '/images/products/gaba-eastern-riddle.jpg',
    status: 'new',
    ru: {
      name: 'ГАБА «Звезда Востока»',
      subtitle: 'Пропечённый ГАБА-улун · Алишань',
      origin: 'Тайвань, Алишань',
      style: 'ГАБА-улун, пропечённый',
      notes: 'Карамель, мёд, сухофрукты',
      description: [
        'Более пропечённый улун с насыщенным ароматом, карамельно-медовыми нотами, оттенками сухофруктов и глубоким тёплым послевкусием.',
      ],
      seoTitle: 'ГАБА «Звезда Востока» | EstasTea',
      seoDesc: 'ГАБА «Звезда Востока» — Более пропечённый улун с насыщенным ароматом, карамельно-медовыми нотами, оттенками сухофруктов и глубоким тёплым послев Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Star of the East”',
      subtitle: 'Roasted GABA oolong · Alishan',
      origin: 'Taiwan, Alishan',
      style: 'GABA oolong, roasted',
      notes: 'Caramel, honey, dried fruit',
      description: [
        'A more heavily roasted oolong with a rich aroma, caramel-and-honey notes, shades of dried fruit and a deep, warm finish.',
      ],
      seoTitle: 'GABA “Star of the East” | EstasTea',
      seoDesc: 'GABA “Star of the East” — A more heavily roasted oolong with a rich aroma, caramel-and-honey notes, shades of dried fruit and a deep, warm finish. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-emperor-secret',
    category: 'gaba-oolong',
    image: '/images/products/gaba-emperor-secret.jpg',
    ru: {
      name: 'ГАБА «Тайна Императора»',
      subtitle: 'Непропечённый ГАБА-улун · Алишань',
      origin: 'Тайвань, Алишань',
      style: 'ГАБА-улун, непропечённый',
      notes: 'Цветы, сливочность, мягкая сладость',
      description: [
        'Непропечённый улун с чистым свежим вкусом, цветочными оттенками, лёгкой сливочностью и мягкой сладостью в послевкусии.',
      ],
      seoTitle: 'ГАБА «Тайна Императора» | EstasTea',
      seoDesc: 'ГАБА «Тайна Императора» — Непропечённый улун с чистым свежим вкусом, цветочными оттенками, лёгкой сливочностью и мягкой сладостью в послевкусии. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Secret of the Emperor”',
      subtitle: 'Unroasted GABA oolong · Alishan',
      origin: 'Taiwan, Alishan',
      style: 'GABA oolong, unroasted',
      notes: 'Florals, cream, soft sweetness',
      description: [
        'An unroasted oolong with a clean, fresh taste, floral shades, a light creaminess and a soft sweetness in the finish.',
      ],
      seoTitle: 'GABA “Secret of the Emperor” | EstasTea',
      seoDesc: 'GABA “Secret of the Emperor” — An unroasted oolong with a clean, fresh taste, floral shades, a light creaminess and a soft sweetness in the finish. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-dragon-secret',
    category: 'gaba-oolong',
    image: '/images/products/gaba-dragon.png',
    featured: true,
    ru: {
      name: 'ГАБА «Тайна Дракона»',
      subtitle: 'GABA Dragon · Шань Лин Си',
      origin: 'Тайвань, Шань Лин Си',
      altitude: '1600 м',
      style: 'ГАБА-улун',
      notes: 'Мёд, фрукты, древесная глубина',
      description: [
        'Эксклюзивный высокогорный улун с медовыми и фруктовыми нотами, утончённой древесной глубиной и долгим мягким послевкусием.',
      ],
      brewing: '90–95 °C · 5 г / 100 мл · 20–30 сек',
      seoTitle: 'ГАБА «Тайна Дракона» | EstasTea',
      seoDesc: 'ГАБА «Тайна Дракона» — Эксклюзивный высокогорный улун с медовыми и фруктовыми нотами, утончённой древесной глубиной и долгим мягким послевкусие Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA “Secret of the Dragon”',
      subtitle: 'GABA Dragon · Shan Lin Xi',
      origin: 'Taiwan, Shan Lin Xi',
      altitude: '1,600 m',
      style: 'GABA oolong',
      notes: 'Honey, fruit, woody depth',
      description: [
        'An exclusive high-mountain oolong with honey and fruit notes, a refined woody depth and a long, soft finish.',
      ],
      brewing: '90–95 °C · 5 g / 100 ml · 20–30 sec',
      seoTitle: 'GABA “Secret of the Dragon” | EstasTea',
      seoDesc: 'GABA “Secret of the Dragon” — An exclusive high-mountain oolong with honey and fruit notes, a refined woody depth and a long, soft finish. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'alpika-lishan-grade-2',
    category: 'light-oolong',
    image: '/images/products/alpika-lishan-grade-2.jpg',
    ru: {
      name: 'Альпика · Ли Шань',
      subtitle: 'Grade 2 · Лишань',
      origin: 'Тайвань, Лишань',
      altitude: '2200–2600 м',
      style: 'Светлый высокогорный улун',
      notes: 'Груша, сладкие фрукты, лёгкое умами',
      description: [
        'Высокогорный улун, сладко-фруктовый, с нотами груши и лёгким умами.',
      ],
      seoTitle: 'Альпика · Ли Шань | EstasTea',
      seoDesc: 'Альпика · Ли Шань — Высокогорный улун, сладко-фруктовый, с нотами груши и лёгким умами. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alpika · Li Shan',
      subtitle: 'Grade 2 · Lishan',
      origin: 'Taiwan, Lishan',
      altitude: '2,200–2,600 m',
      style: 'Light high-mountain oolong',
      notes: 'Pear, sweet fruit, light umami',
      description: [
        'A high-mountain oolong, sweet and fruity, with pear notes and a light umami.',
      ],
      seoTitle: 'Alpika · Li Shan | EstasTea',
      seoDesc: 'Alpika · Li Shan — A high-mountain oolong, sweet and fruity, with pear notes and a light umami. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'the-top-fushoushan-grade-2',
    category: 'light-oolong',
    image: '/images/products/fushoushan.jpg',
    ru: {
      name: 'The Top · Фушоушань',
      subtitle: 'Grade 2 · Фушоушань',
      origin: 'Тайвань, Фушоушань',
      altitude: '2200–2600 м',
      style: 'Светлый высокогорный улун',
      notes: 'Цветы, сливки, высокогорная чистота',
      description: [
        'Редкий высокогорный улун с насыщенным цветочно-сливочным ароматом.',
      ],
      brewing: '90–93 °C · 4–5 г / 100 мл · 15–25 сек',
      seoTitle: 'The Top · Фушоушань | EstasTea',
      seoDesc: 'The Top · Фушоушань — Редкий высокогорный улун с насыщенным цветочно-сливочным ароматом. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'The Top · Fushoushan',
      subtitle: 'Grade 2 · Fushoushan',
      origin: 'Taiwan, Fushoushan',
      altitude: '2,200–2,600 m',
      style: 'Light high-mountain oolong',
      notes: 'Florals, cream, alpine clarity',
      description: [
        'A rare high-mountain oolong with a rich floral-and-cream aroma.',
      ],
      brewing: '90–93 °C · 4–5 g / 100 ml · 15–25 sec',
      seoTitle: 'The Top · Fushoushan | EstasTea',
      seoDesc: 'The Top · Fushoushan — A rare high-mountain oolong with a rich floral-and-cream aroma. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'alpika-lishan-top-grade',
    category: 'light-oolong',
    image: '/images/products/alpika-lishan-top-grade.jpg',
    ru: {
      name: 'Альпика Лишань · Top Grade',
      subtitle: 'Высшая категория · Лишань',
      origin: 'Тайвань, Лишань',
      style: 'Светлый высокогорный улун',
      notes: 'Кремовая текстура, цветы, фрукты, чистое послевкусие',
      description: [
        'Элитный высокогорный улун с Лишань, отличающийся исключительной чистотой вкуса и глубиной.',
        'Плотный, но очень гладкий настой с выраженной природной сладостью, кремовой текстурой и тонкими цветочно-фруктовыми оттенками. Вкус многослойный, с долгим мягким и очень чистым послевкусием, без горечи и резкости.',
      ],
      seoTitle: 'Альпика Лишань · Top Grade | EstasTea',
      seoDesc: 'Альпика Лишань · Top Grade — Элитный высокогорный улун с Лишань, отличающийся исключительной чистотой вкуса и глубиной. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alpika Lishan · Top Grade',
      subtitle: 'Top grade · Lishan',
      origin: 'Taiwan, Lishan',
      style: 'Light high-mountain oolong',
      notes: 'Creamy texture, florals, fruit, clean finish',
      description: [
        'A top-tier high-mountain oolong from Lishan, remarkable for the purity and depth of its taste.',
        'A dense yet very smooth liquor with a pronounced natural sweetness, a creamy texture and fine floral-fruity shades. The taste is layered, with a long, soft and very clean finish, free of bitterness or harshness.',
      ],
      seoTitle: 'Alpika Lishan · Top Grade | EstasTea',
      seoDesc: 'Alpika Lishan · Top Grade — A top-tier high-mountain oolong from Lishan, remarkable for the purity and depth of its taste. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'fushoushan-top-grade',
    category: 'light-oolong',
    image: '/images/products/fushoushan-top-grade.jpg',
    status: 'new',
    ru: {
      name: 'Фушоу Шань Top Grade 1',
      subtitle: 'Высшая категория · Фушоушань',
      origin: 'Тайвань, Фушоушань',
      style: 'Светлый высокогорный улун',
      notes: 'Мёд, сливки, фрукты, бархатистое тело',
      description: [
        'Премиальный высокогорный улун высшей категории с Фушоушань.',
        'Очень глубокий и насыщенный профиль с балансом сладости, плотности и ароматической сложности. Во вкусе — медово-сливочные ноты, лёгкая фруктовость и утончённая цветочность. Настой густой, бархатистый, с длительным и элегантным послевкусием.',
      ],
      seoTitle: 'Фушоу Шань Top Grade 1 | EstasTea',
      seoDesc: 'Фушоу Шань Top Grade 1 — Премиальный высокогорный улун высшей категории с Фушоушань. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Fushou Shan Top Grade 1',
      subtitle: 'Top grade · Fushoushan',
      origin: 'Taiwan, Fushoushan',
      style: 'Light high-mountain oolong',
      notes: 'Honey, cream, fruit, velvet body',
      description: [
        'A premium top-grade high-mountain oolong from Fushoushan.',
        'A very deep and rich profile balancing sweetness, density and aromatic complexity. The taste carries honey-and-cream notes, a light fruitiness and a refined florality. The liquor is thick and velvety, with a long, elegant finish.',
      ],
      seoTitle: 'Fushou Shan Top Grade 1 | EstasTea',
      seoDesc: 'Fushou Shan Top Grade 1 — A premium top-grade high-mountain oolong from Fushoushan. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'emperor-legends-mi-xian',
    category: 'dark-oolong',
    image: '/images/products/emperor.jpg',
    featured: true,
    ru: {
      name: 'Легенды Императора Mi Xian',
      subtitle: 'Mi Xian · тёмный улун',
      origin: 'Тайвань',
      style: 'Тёмный улун',
      notes: 'Цветочный мёд, спелые фрукты',
      description: [
        'Насыщенный улун с цветочным мёдом и фруктовыми нотами.',
      ],
      brewing: '95 °C · 5 г / 100 мл · 20–35 сек',
      seoTitle: 'Легенды Императора Mi Xian | EstasTea',
      seoDesc: 'Легенды Императора Mi Xian — Насыщенный улун с цветочным мёдом и фруктовыми нотами. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Emperor’s Legends Mi Xian',
      subtitle: 'Mi Xian · dark oolong',
      origin: 'Taiwan',
      style: 'Dark oolong',
      notes: 'Floral honey, ripe fruit',
      description: [
        'A rich oolong with floral honey and fruit notes.',
      ],
      brewing: '95 °C · 5 g / 100 ml · 20–35 sec',
      seoTitle: 'Emperor’s Legends Mi Xian | EstasTea',
      seoDesc: 'Emperor’s Legends Mi Xian — A rich oolong with floral honey and fruit notes. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'red-oolong-master-lion',
    category: 'dark-oolong',
    image: '/images/products/red-oolong-master-lion.jpg',
    ru: {
      name: 'Красный улун Али Шань · Мастер Лион',
      subtitle: 'Red Oolong · Мастер Лион',
      origin: 'Тайвань, Алишань',
      style: 'Красный улун',
      notes: 'Маслянистое тело, цветочный аромат',
      description: [
        'Мягкий красный улун с маслянистым телом и цветочным ароматом.',
      ],
      seoTitle: 'Красный улун Али Шань · Мастер Лион | EstasTea',
      seoDesc: 'Красный улун Али Шань · Мастер Лион — Мягкий красный улун с маслянистым телом и цветочным ароматом. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alishan Red Oolong · Master Lion',
      subtitle: 'Red Oolong · Master Lion',
      origin: 'Taiwan, Alishan',
      style: 'Red oolong',
      notes: 'Oily body, floral aroma',
      description: [
        'A soft red oolong with an oily body and a floral aroma.',
      ],
      seoTitle: 'Alishan Red Oolong · Master Lion | EstasTea',
      seoDesc: 'Alishan Red Oolong · Master Lion — A soft red oolong with an oily body and a floral aroma. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'red-oolong-oliver-stone',
    category: 'dark-oolong',
    image: '/images/products/oliver-stone.jpg',
    ru: {
      name: 'Красный улун Али Шань · Оливер Стоун',
      subtitle: 'Red Oolong · Oliver Stone',
      origin: 'Тайвань, Алишань',
      style: 'Красный улун',
      notes: 'Маслянистое тело, цветы, лёгкий дымок',
      description: [
        'Красный улун с маслянистым телом, цветочным ароматом и лёгким дымком.',
      ],
      brewing: '93–96 °C · 5 г / 100 мл · 20–30 сек',
      seoTitle: 'Красный улун Али Шань · Оливер Стоун | EstasTea',
      seoDesc: 'Красный улун Али Шань · Оливер Стоун — Красный улун с маслянистым телом, цветочным ароматом и лёгким дымком. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alishan Red Oolong · Oliver Stone',
      subtitle: 'Red Oolong · Oliver Stone',
      origin: 'Taiwan, Alishan',
      style: 'Red oolong',
      notes: 'Oily body, florals, light smoke',
      description: [
        'A red oolong with an oily body, a floral aroma and a light smokiness.',
      ],
      brewing: '93–96 °C · 5 g / 100 ml · 20–30 sec',
      seoTitle: 'Alishan Red Oolong · Oliver Stone | EstasTea',
      seoDesc: 'Alishan Red Oolong · Oliver Stone — A red oolong with an oily body, a floral aroma and a light smokiness. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'shan-lin-xi-dong-ding',
    category: 'dong-ding',
    image: '/images/products/shan-lin-xi-dong-ding.jpg',
    ru: {
      name: 'Шань Линь Си Дун Дин',
      subtitle: 'Классический Дун Дин',
      origin: 'Тайвань, Шань Лин Си',
      altitude: '1200 м',
      style: 'Дун Дин, мягкая обжарка',
      notes: 'Сладковато-древесные ноты',
      description: [
        'Классический улун с мягкой обжаркой, сладковато-древесными нотами.',
      ],
      seoTitle: 'Шань Линь Си Дун Дин | EstasTea',
      seoDesc: 'Шань Линь Си Дун Дин — Классический улун с мягкой обжаркой, сладковато-древесными нотами. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Shan Lin Xi Dong Ding',
      subtitle: 'Classic Dong Ding',
      origin: 'Taiwan, Shan Lin Xi',
      altitude: '1,200 m',
      style: 'Dong Ding, light roast',
      notes: 'Sweet, woody notes',
      description: [
        'A classic lightly roasted oolong with sweet, woody notes.',
      ],
      seoTitle: 'Shan Lin Xi Dong Ding | EstasTea',
      seoDesc: 'Shan Lin Xi Dong Ding — A classic lightly roasted oolong with sweet, woody notes. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'shan-lin-xi-dong-ding-hong-shui',
    category: 'dong-ding',
    image: '/images/products/shan-lin-xi-dong-ding-hong-shui.jpg',
    ru: {
      name: 'Шань Линь Си Дун Дин Хун Шуй',
      subtitle: 'Hong Shui · глубокая ферментация',
      origin: 'Тайвань, Шань Лин Си',
      altitude: '1600 м',
      style: 'Дун Дин Хун Шуй',
      notes: 'Сухофрукты, глубокая ферментация',
      description: [
        'Более насыщенный улун с глубоким ферментированным вкусом и тонами сухофруктов.',
      ],
      seoTitle: 'Шань Линь Си Дун Дин Хун Шуй | EstasTea',
      seoDesc: 'Шань Линь Си Дун Дин Хун Шуй — Более насыщенный улун с глубоким ферментированным вкусом и тонами сухофруктов. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Shan Lin Xi Dong Ding Hong Shui',
      subtitle: 'Hong Shui · deep oxidation',
      origin: 'Taiwan, Shan Lin Xi',
      altitude: '1,600 m',
      style: 'Dong Ding Hong Shui',
      notes: 'Dried fruit, deep oxidation',
      description: [
        'A richer oolong with a deep fermented taste and tones of dried fruit.',
      ],
      seoTitle: 'Shan Lin Xi Dong Ding Hong Shui | EstasTea',
      seoDesc: 'Shan Lin Xi Dong Ding Hong Shui — A richer oolong with a deep fermented taste and tones of dried fruit. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'mountain-spring-master-zhao',
    category: 'dong-ding',
    image: '/images/products/mountain-spring-master-zhao.jpg',
    ru: {
      name: '«Горный Источник» · Мастер Чжао',
      subtitle: 'Mountain Spring · Мастер Чжао',
      origin: 'Тайвань, Лугу',
      style: 'Дун Дин',
      notes: 'Древесина, орех, живая теплота',
      description: [
        'Тёплый, живой вкус с древесно-ореховыми нотами.',
      ],
      seoTitle: '«Горный Источник» · Мастер Чжао | EstasTea',
      seoDesc: '«Горный Источник» · Мастер Чжао — Тёплый, живой вкус с древесно-ореховыми нотами. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: '“Mountain Spring” · Master Zhao',
      subtitle: 'Mountain Spring · Master Zhao',
      origin: 'Taiwan, Lugu',
      style: 'Dong Ding',
      notes: 'Wood, nut, living warmth',
      description: [
        'A warm, living taste with woody and nutty notes.',
      ],
      seoTitle: '“Mountain Spring” · Master Zhao | EstasTea',
      seoDesc: '“Mountain Spring” · Master Zhao — A warm, living taste with woody and nutty notes. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'cloud-temple-master-zhao',
    category: 'dong-ding',
    image: '/images/products/dong-ding.png',
    featured: true,
    ru: {
      name: '«Храм Облаков» · Мастер Чжао',
      subtitle: 'Cloud Temple · Мастер Чжао',
      origin: 'Тайвань, Лугу, Дун Дин',
      style: 'Дун Дин',
      notes: 'Маслянистое тело, цветы, дымок',
      description: [
        'Маслянистое тело, долгое послевкусие с цветами и дымком.',
      ],
      brewing: '95 °C · 5 г / 100 мл · проливы 20–30 сек',
      seoTitle: '«Храм Облаков» · Мастер Чжао | EstasTea',
      seoDesc: '«Храм Облаков» · Мастер Чжао — Маслянистое тело, долгое послевкусие с цветами и дымком. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: '“Cloud Temple” · Master Zhao',
      subtitle: 'Cloud Temple · Master Zhao',
      origin: 'Taiwan, Lugu, Dong Ding',
      style: 'Dong Ding',
      notes: 'Oily body, florals, smoke',
      description: [
        'An oily body and a long finish with florals and a touch of smoke.',
      ],
      brewing: '95 °C · 5 g / 100 ml · 20–30 sec infusions',
      seoTitle: '“Cloud Temple” · Master Zhao | EstasTea',
      seoDesc: '“Cloud Temple” · Master Zhao — An oily body and a long finish with florals and a touch of smoke. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'red-tea-master-wei-shien',
    category: 'red',
    image: '/images/products/red-tea-master-wei-shien.jpg',
    status: 'seasonal',
    ru: {
      name: 'Красный чай · Master Wei Shien',
      subtitle: 'Али Шань · Master Wei Shien',
      origin: 'Тайвань, Алишань',
      altitude: '1500 м',
      style: 'Красный чай',
      notes: 'Сезонный сбор',
      description: [
        'Высокогорный красный чай от мастера Wei Shien, сезонный сбор.',
      ],
      seoTitle: 'Красный чай · Master Wei Shien | EstasTea',
      seoDesc: 'Красный чай · Master Wei Shien — Высокогорный красный чай от мастера Wei Shien, сезонный сбор. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Red Tea · Master Wei Shien',
      subtitle: 'Alishan · Master Wei Shien',
      origin: 'Taiwan, Alishan',
      altitude: '1,500 m',
      style: 'Red tea',
      notes: 'Seasonal harvest',
      description: [
        'A high-mountain red tea from Master Wei Shien, a seasonal harvest.',
      ],
      seoTitle: 'Red Tea · Master Wei Shien | EstasTea',
      seoDesc: 'Red Tea · Master Wei Shien — A high-mountain red tea from Master Wei Shien, a seasonal harvest. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'ruby-18-sun-moon-lake',
    category: 'red',
    image: '/images/products/ruby-18-sun-moon-lake.jpg',
    status: 'new',
    ru: {
      name: 'Ruby 18 · Озеро Солнца и Луны',
      subtitle: 'Sun Moon Lake · Ruby 18',
      origin: 'Тайвань, Озеро Солнца и Луны',
      style: 'Красный чай',
      notes: 'Корица, мята, мёд, карамель',
      description: [
        'Премиальный тайваньский чёрный чай с ярким профилем: ноты корицы и мяты, медово-карамельная сладость, плотное тело и долгое согревающее послевкусие.',
      ],
      seoTitle: 'Ruby 18 · Озеро Солнца и Луны | EstasTea',
      seoDesc: 'Ruby 18 · Озеро Солнца и Луны — Премиальный тайваньский чёрный чай с ярким профилем: ноты корицы и мяты, медово-карамельная сладость, плотное тело и дол Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Ruby 18 · Sun Moon Lake',
      subtitle: 'Sun Moon Lake · Ruby 18',
      origin: 'Taiwan, Sun Moon Lake',
      style: 'Red tea',
      notes: 'Cinnamon, mint, honey, caramel',
      description: [
        'A premium Taiwanese black tea with a vivid profile: cinnamon and mint notes, a honey-caramel sweetness, a dense body and a long warming finish.',
      ],
      seoTitle: 'Ruby 18 · Sun Moon Lake | EstasTea',
      seoDesc: 'Ruby 18 · Sun Moon Lake — A premium Taiwanese black tea with a vivid profile: cinnamon and mint notes, a honey-caramel sweetness, a dense body and Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'white-alishan-qing-xin',
    category: 'white',
    image: '/images/products/white-alishan-qing-xin.jpg',
    ru: {
      name: 'Белый чай «Али Шань»',
      subtitle: 'Qing Xin / Chin Xin Oolong',
      origin: 'Тайвань, Алишань',
      cultivar: 'Qing Xin / Chin Xin Oolong',
      style: 'Белый чай',
      notes: 'Цветы, лёгкая фруктовость, мёд, бархатистость',
      description: [
        'Очень вкусный высокогорный белый чай с мягким и чистым профилем.',
        'Во вкусе — нежная цветочность, лёгкая фруктовость, мягкая медовая сладость и бархатистая текстура. Настой деликатный, но глубокий, с длинным и гармоничным послевкусием.',
        'Редкий весенний высокогорный чай, произведённый в небольшом объёме в сезон ограниченного сбора.',
      ],
      seoTitle: 'Белый чай «Али Шань» | EstasTea',
      seoDesc: 'Белый чай «Али Шань» — Очень вкусный высокогорный белый чай с мягким и чистым профилем. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alishan White Tea',
      subtitle: 'Qing Xin / Chin Xin Oolong',
      origin: 'Taiwan, Alishan',
      cultivar: 'Qing Xin / Chin Xin Oolong',
      style: 'White tea',
      notes: 'Florals, light fruit, honey, velvet',
      description: [
        'A very fine high-mountain white tea with a soft, clean profile.',
        'The taste carries a delicate florality, a light fruitiness, a soft honeyed sweetness and a velvety texture. The liquor is delicate yet deep, with a long, harmonious finish.',
        'A rare spring high-mountain tea, made in a small volume during a limited picking season.',
      ],
      seoTitle: 'Alishan White Tea | EstasTea',
      seoDesc: 'Alishan White Tea — A very fine high-mountain white tea with a soft, clean profile. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'white-alishan-n23-qing-yun',
    category: 'white',
    image: '/images/products/white-alishan-n23-qing-yun.jpg',
    status: 'new',
    ru: {
      name: 'Белый чай Али Шань · Qin Yuan',
      subtitle: 'Особый сорт куста',
      origin: 'Тайвань, Алишань',
      cultivar: 'Qin Yuan',
      style: 'Белый чай',
      notes: 'Цветы, мёд, деликатная фруктовость',
      description: [
        'Очень лёгкий и чистый весенний белый чай с мягким, воздушным профилем.',
        'Во вкусе — нежная цветочность, лёгкая медовая сладость и деликатная фруктовая нота. Настой прозрачный и ровный, с очень мягким, чистым послевкусием.',
        'Редкий весенний высокогорный чай, произведённый в небольшом объёме в сезон ограниченного сбора.',
      ],
      seoTitle: 'Белый чай Али Шань · Qin Yuan | EstasTea',
      seoDesc: 'Белый чай Али Шань · Qin Yuan — Очень лёгкий и чистый весенний белый чай с мягким, воздушным профилем. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Alishan White Tea · Qin Yuan',
      subtitle: 'A distinctive cultivar',
      origin: 'Taiwan, Alishan',
      cultivar: 'Qin Yuan',
      style: 'White tea',
      notes: 'Florals, honey, delicate fruit',
      description: [
        'A very light and clean spring white tea with a soft, airy profile.',
        'The taste carries a delicate florality, a light honeyed sweetness and a fine fruit note. The liquor is clear and even, with a very soft, clean finish.',
        'A rare spring high-mountain tea, made in a small volume during a limited picking season.',
      ],
      seoTitle: 'Alishan White Tea · Qin Yuan | EstasTea',
      seoDesc: 'Alishan White Tea · Qin Yuan — A very light and clean spring white tea with a soft, airy profile. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'aged-oolong-master-lin-30',
    category: 'aged',
    image: '/images/products/aged-oolong-master-lin-30.jpg',
    ru: {
      name: '30-летний улун от Мастера Лина',
      subtitle: 'Выдержка 30 лет',
      origin: 'Тайвань',
      style: 'Выдержанный улун',
      year: '30 лет выдержки',
      notes: 'Многолетняя выдержка',
      description: [
        'Выдержанный тайваньский улун с многолетней историей.',
      ],
      seoTitle: '30-летний улун от Мастера Лина | EstasTea',
      seoDesc: '30-летний улун от Мастера Лина — Выдержанный тайваньский улун с многолетней историей. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: '30-Year Aged Oolong by Master Lin',
      subtitle: '30 years of ageing',
      origin: 'Taiwan',
      style: 'Aged oolong',
      year: '30 years aged',
      notes: 'Decades of ageing',
      description: [
        'An aged Taiwanese oolong with a history spanning decades.',
      ],
      seoTitle: '30-Year Aged Oolong by Master Lin | EstasTea',
      seoDesc: '30-Year Aged Oolong by Master Lin — An aged Taiwanese oolong with a history spanning decades. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'lao-cha-pinglin-30',
    category: 'aged',
    image: '/images/products/lao-cha-pinglin-30.jpg',
    ru: {
      name: 'Лао Ча Пин Линь · 30 лет',
      subtitle: 'Lao Cha · Пин Линь',
      origin: 'Тайвань, Пин Линь',
      style: 'Выдержанный чай',
      year: '30 лет выдержки',
      notes: 'Тридцатилетняя выдержка',
      description: [
        'Выдержанный чай из Пин Линь с тридцатилетней историей.',
      ],
      seoTitle: 'Лао Ча Пин Линь · 30 лет | EstasTea',
      seoDesc: 'Лао Ча Пин Линь · 30 лет — Выдержанный чай из Пин Линь с тридцатилетней историей. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Lao Cha Pinglin · 30 Years',
      subtitle: 'Lao Cha · Pinglin',
      origin: 'Taiwan, Pinglin',
      style: 'Aged tea',
      year: '30 years aged',
      notes: 'Thirty years of ageing',
      description: [
        'An aged tea from Pinglin with a thirty-year history.',
      ],
      seoTitle: 'Lao Cha Pinglin · 30 Years | EstasTea',
      seoDesc: 'Lao Cha Pinglin · 30 Years — An aged tea from Pinglin with a thirty-year history. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'mi-shian-hon-cha-pinglin-2026',
    category: 'competition',
    image: '/images/products/mi-shian-hon-cha-pinglin-2026.jpg',
    ru: {
      name: 'Mi Shian Hon Cha · Pin Ling',
      subtitle: 'Summer 2026 · конкурсный чай',
      origin: 'Тайвань, Пин Линь',
      style: 'Конкурсный чай',
      year: 'Лето 2026',
      notes: 'Новый сезон',
      description: [
        'Конкурсный тайваньский чай из Пин Линь нового сезона.',
      ],
      seoTitle: 'Mi Shian Hon Cha · Pin Ling | EstasTea',
      seoDesc: 'Mi Shian Hon Cha · Pin Ling — Конкурсный тайваньский чай из Пин Линь нового сезона. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Mi Shian Hon Cha · Pin Ling',
      subtitle: 'Summer 2026 · competition tea',
      origin: 'Taiwan, Pinglin',
      style: 'Competition tea',
      year: 'Summer 2026',
      notes: 'New season',
      description: [
        'A Taiwanese competition tea from Pinglin, new season.',
      ],
      seoTitle: 'Mi Shian Hon Cha · Pin Ling | EstasTea',
      seoDesc: 'Mi Shian Hon Cha · Pin Ling — A Taiwanese competition tea from Pinglin, new season. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'gaba-5-star-lishan',
    category: 'gaba-special',
    image: '/images/products/gaba-5-star-lishan-1.jpg',
    images: [
      '/images/products/gaba-5-star-lishan-1.jpg',
      '/images/products/gaba-5-star-lishan-3.jpg',
      '/images/products/gaba-5-star-lishan-4.jpg',
      '/images/products/gaba-5-star-lishan-5.jpg',
    ],
    status: 'sold-out',
    ru: {
      name: 'GABA 5 Star · Li Shan',
      subtitle: 'Особая коллекция GABA',
      origin: 'Тайвань, Лишань',
      style: 'ГАБА, особая коллекция',
      notes: 'Особая коллекция',
      description: [
        'ГАБА-чай особой коллекции с Лишань.',
      ],
      seoTitle: 'GABA 5 Star · Li Shan | EstasTea',
      seoDesc: 'GABA 5 Star · Li Shan — ГАБА-чай особой коллекции с Лишань. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'GABA 5 Star · Li Shan',
      subtitle: 'Special GABA collection',
      origin: 'Taiwan, Lishan',
      style: 'GABA, special collection',
      notes: 'Special collection',
      description: [
        'A special-collection GABA tea from Lishan.',
      ],
      seoTitle: 'GABA 5 Star · Li Shan | EstasTea',
      seoDesc: 'GABA 5 Star · Li Shan — A special-collection GABA tea from Lishan. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'shu-puerh-90s-scholar',
    category: 'shu-puerh',
    image: '/images/products/shu-puerh-90s-scholar-1.jpg',
    images: [
      '/images/products/shu-puerh-90s-scholar-1.jpg',
      '/images/products/shu-puerh-90s-scholar-2.jpg',
    ],
    ru: {
      name: 'Шу Пуэр 90-х «Учёный»',
      subtitle: 'Выдержка с 1990-х',
      origin: 'Китай',
      style: 'Шу пуэр',
      year: '1990-е',
      notes: 'Шоколад, сгущёнка, грецкий орех, чернослив',
      description: [
        'Выдержанный шу пуэр с глубоким, насыщенным и маслянистым характером.',
        'Вкусовой профиль — глубокий шоколад, варёная сгущёнка, грецкий орех, чернослив. Минеральная основа и долгое сладкое ореховое послевкусие.',
        'Мощный и концентрированный чай с выраженным эффектом ясности и спокойной собранности.',
      ],
      seoTitle: 'Шу Пуэр 90-х «Учёный» | EstasTea',
      seoDesc: 'Шу Пуэр 90-х «Учёный» — Выдержанный шу пуэр с глубоким, насыщенным и маслянистым характером. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: '1990s Shu Pu-erh “The Scholar”',
      subtitle: 'Aged since the 1990s',
      origin: 'China',
      style: 'Shu pu-erh',
      year: '1990s',
      notes: 'Chocolate, condensed milk, walnut, prune',
      description: [
        'An aged shu pu-erh with a deep, rich and oily character.',
        'The profile runs to deep chocolate, boiled condensed milk, walnut and prune, over a mineral base with a long, sweet nutty finish.',
        'A powerful, concentrated tea with a pronounced effect of clarity and calm focus.',
      ],
      seoTitle: '1990s Shu Pu-erh “The Scholar” | EstasTea',
      seoDesc: '1990s Shu Pu-erh “The Scholar” — An aged shu pu-erh with a deep, rich and oily character. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'shu-dayi-0562-2005',
    category: 'shu-puerh',
    image: '/images/products/shu-0562.jpg',
    ru: {
      name: 'Шу Пуэр Da Yi · 2005 · Рецепт 0562',
      subtitle: 'Menghai (Da Yi) · рецепт 0562',
      origin: 'Китай, Мэнхай (Da Yi)',
      style: 'Шу пуэр, коллекционный',
      year: '2005',
      storage: 'Тайваньское хранение',
      notes: 'Чёрный шоколад, чернослив, грецкий орех, старая древесина',
      description: [
        'Коллекционный шу пуэр фабрики Menghai (Da Yi) 2005 года, рецепт 0562.',
        'Чай с утончённым, глубоким и бархатистым профилем. В аромате — чёрный шоколад, чернослив, грецкий орех и старая древесина.',
        'Настой густой и маслянистый. Во вкусе — сладкая патока, какао-бобы и печёное яблоко. Долгое сладкое послевкусие с минеральной свежестью.',
      ],
      brewing: '100 °C · 6–8 г / 100 мл · промывка + короткие проливы',
      seoTitle: 'Шу Пуэр Da Yi · 2005 · Рецепт 0562 | EstasTea',
      seoDesc: 'Шу Пуэр Da Yi · 2005 · Рецепт 0562 — Коллекционный шу пуэр фабрики Menghai (Da Yi) 2005 года, рецепт 0562. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Shu Pu-erh Da Yi · 2005 · Recipe 0562',
      subtitle: 'Menghai (Da Yi) · recipe 0562',
      origin: 'China, Menghai (Da Yi)',
      style: 'Shu pu-erh, collectible',
      year: '2005',
      storage: 'Taiwan storage',
      notes: 'Dark chocolate, prune, walnut, old wood',
      description: [
        'A collectible 2005 shu pu-erh from the Menghai (Da Yi) factory, recipe 0562.',
        'A tea with a refined, deep and velvety profile. The aroma carries dark chocolate, prune, walnut and old wood.',
        'The liquor is thick and oily. The taste brings sweet molasses, cocoa beans and baked apple, with a long sweet finish and a mineral freshness.',
      ],
      brewing: '100 °C · 6–8 g / 100 ml · rinse, then short infusions',
      seoTitle: 'Shu Pu-erh Da Yi · 2005 · Recipe 0562 | EstasTea',
      seoDesc: 'Shu Pu-erh Da Yi · 2005 · Recipe 0562 — A collectible 2005 shu pu-erh from the Menghai (Da Yi) factory, recipe 0562. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'shu-dayi-7572',
    category: 'shu-puerh',
    image: '/images/products/shu-7572.jpeg',
    ru: {
      name: 'Шу Пуэр Da Yi · 7572',
      subtitle: 'Menghai (Da Yi) · рецепт 7572',
      origin: 'Китай, Мэнхай (Da Yi)',
      style: 'Шу пуэр',
      notes: 'Чернослив, ржаной хлеб, патока, древесина',
      description: [
        'Классический рецепт фабрики Menghai (Da Yi), один из наиболее известных рецептов шу пуэра.',
        'Мощный, глубокий и насыщенный чай с плотным телом и стабильным вкусом от пролива к проливу.',
        'В аромате — чернослив, древесина, сладкая патока. Во вкусе — ржаной хлеб, гречишная патока, чернослив и сухая древесина. Долгое сладко-миндальное послевкусие.',
      ],
      brewing: '100 °C · 6–8 г / 100 мл · промывка + короткие проливы',
      seoTitle: 'Шу Пуэр Da Yi · 7572 | EstasTea',
      seoDesc: 'Шу Пуэр Da Yi · 7572 — Классический рецепт фабрики Menghai (Da Yi), один из наиболее известных рецептов шу пуэра. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Shu Pu-erh Da Yi · 7572',
      subtitle: 'Menghai (Da Yi) · recipe 7572',
      origin: 'China, Menghai (Da Yi)',
      style: 'Shu pu-erh',
      notes: 'Prune, rye bread, molasses, wood',
      description: [
        'The classic Menghai (Da Yi) recipe, one of the best-known shu pu-erh recipes there is.',
        'A powerful, deep and rich tea with a dense body and a taste that holds steady from infusion to infusion.',
        'The aroma carries prune, wood and sweet molasses. The taste brings rye bread, buckwheat molasses, prune and dry wood, with a long sweet-almond finish.',
      ],
      brewing: '100 °C · 6–8 g / 100 ml · rinse, then short infusions',
      seoTitle: 'Shu Pu-erh Da Yi · 7572 | EstasTea',
      seoDesc: 'Shu Pu-erh Da Yi · 7572 — The classic Menghai (Da Yi) recipe, one of the best-known shu pu-erh recipes there is. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'xiaguan-shu-2004',
    category: 'shu-puerh',
    image: '/images/products/xiaguan-shu-2004-1.jpg',
    images: [
      '/images/products/xiaguan-shu-2004-1.jpg',
      '/images/products/xiaguan-shu-2004-2.jpg',
      '/images/products/xiaguan-shu-2004-3.jpg',
    ],
    ru: {
      name: 'Сягуань Шу Пуэр · 2004',
      subtitle: 'Прессованный то ча · тайваньское хранение',
      origin: 'Китай, Сягуань (Xiaguan)',
      style: 'Шу пуэр, то ча',
      year: '2004',
      storage: 'Тайваньское хранение',
      notes: 'Древесина, чернослив, какао, сухофрукты',
      description: [
        'Редкий выдержанный шу пуэр с более чем двадцатилетним тайваньским хранением.',
        'Плотный, глубокий и мягкий профиль без резкости. В первых проливах — благородная древесина, чернослив и какао. Далее появляются сухофрукты, бархатистость и глубокая древесная сладость.',
        'Долгое, чистое и согревающее послевкусие. Чай для коллекционеров и ценителей выдержанного пуэра.',
      ],
      seoTitle: 'Сягуань Шу Пуэр · 2004 | EstasTea',
      seoDesc: 'Сягуань Шу Пуэр · 2004 — Редкий выдержанный шу пуэр с более чем двадцатилетним тайваньским хранением. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Xiaguan Shu Pu-erh · 2004',
      subtitle: 'Pressed tuo cha · Taiwan storage',
      origin: 'China, Xiaguan Tea Factory',
      style: 'Shu pu-erh, tuo cha',
      year: '2004',
      storage: 'Taiwan storage',
      notes: 'Wood, prune, cocoa, dried fruit',
      description: [
        'A rare aged shu pu-erh with more than twenty years of Taiwan storage.',
        'A dense, deep and soft profile with no harshness. The first infusions give noble wood, prune and cocoa; later ones bring dried fruit, a velvety body and a deep woody sweetness.',
        'A long, clean and warming finish. A tea for collectors and lovers of aged pu-erh.',
      ],
      seoTitle: 'Xiaguan Shu Pu-erh · 2004 | EstasTea',
      seoDesc: 'Xiaguan Shu Pu-erh · 2004 — A rare aged shu pu-erh with more than twenty years of Taiwan storage. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'dayi-7542-2009',
    category: 'collectible-puerh',
    image: '/images/products/dayi-7542-2009.jpg',
    featured: true,
    ru: {
      name: 'DaYi 7542 · 2009 · Партия 901',
      subtitle: 'Da Yi · рецепт 7542, партия 901',
      origin: 'Китай, Мэнхай (Da Yi)',
      style: 'Шэн пуэр, коллекционный',
      year: '2009',
      storage: 'Тайваньское хранение',
      notes: 'Глубина, структура, благородная зрелость',
      description: [
        'Легендарный рецепт 7542 от фабрики Da Yi.',
        'Мощный, сбалансированный и престижный пуэр с глубиной, которую раскрывает многолетнее хранение.',
        'Тайваньское хранение позволило чаю сохранить структуру и постепенно приобрести благородную зрелость.',
      ],
      brewing: '95–100 °C · 5–7 г / 100 мл · короткая промывка, затем 10–20 сек',
      seoTitle: 'DaYi 7542 · 2009 · Партия 901 | EstasTea',
      seoDesc: 'DaYi 7542 · 2009 · Партия 901 — Легендарный рецепт 7542 от фабрики Da Yi. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'DaYi 7542 · 2009 · Batch 901',
      subtitle: 'Da Yi · recipe 7542, batch 901',
      origin: 'China, Menghai (Da Yi)',
      style: 'Sheng pu-erh, collectible',
      year: '2009',
      storage: 'Taiwan storage',
      notes: 'Depth, structure, noble maturity',
      description: [
        'The legendary 7542 recipe from the Da Yi factory.',
        'A powerful, balanced and prestigious pu-erh whose depth is drawn out by years of storage.',
        'Taiwan storage has let the tea keep its structure while gradually taking on a noble maturity.',
      ],
      brewing: '95–100 °C · 5–7 g / 100 ml · brief rinse, then 10–20 sec',
      seoTitle: 'DaYi 7542 · 2009 · Batch 901 | EstasTea',
      seoDesc: 'DaYi 7542 · 2009 · Batch 901 — The legendary 7542 recipe from the Da Yi factory. Wholesale and B2B supply from Taiwan.',
    },
  },
  {
    slug: 'aged-sheng-1980s',
    category: 'collectible-puerh',
    image: '/images/products/aged-sheng.jpg',
    ru: {
      name: 'Редкий старый шэн пуэр · 1980-е',
      subtitle: 'Около 40 лет ферментации в бамбуке',
      origin: 'Китай',
      style: 'Шэн пуэр, выдержанный',
      year: '1980-е',
      notes: 'Мягкость, сладость, зрелость',
      description: [
        'Почти как шу пуэр, но слаще.',
        'Около 40 лет естественной ферментации в бамбуке.',
        'Мягкий, сладкий и выдержанный шэн пуэр с уникальной историей.',
      ],
      brewing: '95–100 °C · 5–6 г / 100 мл · бережная промывка',
      seoTitle: 'Редкий старый шэн пуэр · 1980-е | EstasTea',
      seoDesc: 'Редкий старый шэн пуэр · 1980-е — Почти как шу пуэр, но слаще. Опт и B2B-поставки с Тайваня.',
    },
    en: {
      name: 'Rare Aged Sheng Pu-erh · 1980s',
      subtitle: 'Around 40 years fermenting in bamboo',
      origin: 'China',
      style: 'Sheng pu-erh, aged',
      year: '1980s',
      notes: 'Softness, sweetness, maturity',
      description: [
        'Almost like a shu pu-erh, but sweeter.',
        'Around forty years of natural fermentation inside bamboo.',
        'A soft, sweet and well-aged sheng pu-erh with a history of its own.',
      ],
      brewing: '95–100 °C · 5–6 g / 100 ml · a gentle rinse',
      seoTitle: 'Rare Aged Sheng Pu-erh · 1980s | EstasTea',
      seoDesc: 'Rare Aged Sheng Pu-erh · 1980s — Almost like a shu pu-erh, but sweeter. Wholesale and B2B supply from Taiwan.',
    },
  },
];
